name: Python package

on:
  push:
    branches:
      - master
      - '*.*.*'

  pull_request:
    branches:
      - master
      - '*.*.*'

  schedule:
    - cron: '0 6 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
        django-version: [ 20, 21, 22, 30, 31 ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Tox and any other packages
        run: |
          pip install tox

      - name: Run Tox
        run: tox -e py-django${{ matrix.django-version }}

      - name: Upload coverage to Codecov
        if: matrix.python-version == 3.9 && matrix.django-version == 31
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    continue-on-error: true
    needs: test

    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Creating Built Distributions
        run: python setup.py sdist

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
          skip_existing: true
